FROM nginx:alpine

# Создаем необходимые директории
RUN mkdir -p /etc/nginx/tls /usr/share/nginx/html/uploads

# Копируем конфигурационные файлы
COPY nginx_combined/conf.d/default.conf /etc/nginx/conf.d/default.conf
COPY nginx_combined/conf.d/upstream.conf /etc/nginx/conf.d/upstream.conf
# Создаем директорию для логов
RUN mkdir -p /var/log/nginx

# Устанавливаем правильные разрешения для директории uploads
RUN chmod -R 755 /usr/share/nginx/html/uploads

# Открываем порты
EXPOSE 80 8443