FROM nginx:latest

RUN mkdir -p /etc/nginx/auth

COPY prometheus_proxy.conf /etc/nginx/conf.d/default.conf

COPY nginx/conf.d/upstream.conf /etc/nginx/conf.d/upstream.conf
COPY nginx/auth/.htpasswd /etc/nginx/auth/.htpasswd
