import { Alert } from '../alermanager.types';

export function generateAlertEmailHtml(alert: Alert): string {
    return `
        <div style="font-family: Arial, sans-serif; padding: 20px; max-width: 600px;">
            <h2 style="color: ${getSeverityColor(alert.labels.severity)}">
                🚨 ${alert.labels.alertname}
            </h2>
            <div style="margin: 20px 0; padding: 15px; border-left: 4px solid ${getSeverityColor(alert.labels.severity)};">
                <p><strong>Status:</strong> ${alert.status.toUpperCase()}</p>
                <p><strong>Severity:</strong> ${alert.labels.severity.toUpperCase()}</p>
                <p><strong>Description:</strong> ${alert.annotations.description}</p>
                <p><strong>Instance:</strong> ${alert.labels.instance}</p>
                <p><strong>Started:</strong> ${new Date(alert.startsAt).toLocaleString()}</p>
                ${alert.status === 'resolved' ? 
                    `<p><strong>Resolved:</strong> ${new Date(alert.endsAt).toLocaleString()}</p>` 
                    : ''}
            </div>
            <div style="font-size: 12px; color: #666;">
                <p>Generated by HW Monitor</p>
            </div>
        </div>
    `;
}

export function generateAlertTelegramText(alert: Alert): string {
    return `
🚨 *${alert.labels.alertname}*
*Status:* ${alert.status.toUpperCase()}
*Severity:* ${alert.labels.severity.toUpperCase()}
*Description:* ${alert.annotations.description}
*Instance:* ${alert.labels.instance}
*Started:* ${new Date(alert.startsAt).toLocaleString()}
${alert.status === 'resolved' ? `*Resolved:* ${new Date(alert.endsAt).toLocaleString()}` : ''}
`.trim();
}

function getSeverityColor(severity: string): string {
    switch (severity.toLowerCase()) {
        case 'critical':
            return '#dc3545';
        case 'warning':
            return '#ffc107';
        default:
            return '#17a2b8';
    }
}