import { Alert } from '../alermanager.types'

export function generateAlertEmailHtml(alert: Alert): string {
	// Проверяем, является ли это алертом о смене оборудования
	const isHardwareChange =
		alert.labels.alertname === 'Hardware_Change_Detected' ||
		alert.labels.category === 'hardware_change'

	// Русские заголовки для алерта о смене оборудования
	const statusText = isHardwareChange ? 'Статус' : 'Status'
	const severityText = isHardwareChange ? 'Приоритет' : 'Severity'
	const descriptionText = isHardwareChange ? 'Описание' : 'Description'
	const instanceText = isHardwareChange ? 'Устройство' : 'Instance'
	const startedText = isHardwareChange ? 'Обнаружено' : 'Started'
	const resolvedText = isHardwareChange ? 'Устранено' : 'Resolved'
	const generatedText = isHardwareChange
		? 'Сгенерировано системой мониторинга оборудования'
		: 'Generated by HW Monitor'

	// Русские значения для алерта о смене оборудования
	const statusValue = isHardwareChange
		? alert.status.toUpperCase() === 'FIRING'
			? 'АКТИВЕН'
			: 'УСТРАНЕН'
		: alert.status.toUpperCase()

	const severityValue = isHardwareChange
		? alert.labels.severity.toUpperCase() === 'CRITICAL'
			? 'КРИТИЧЕСКАЯ'
			: alert.labels.severity.toUpperCase() === 'WARNING'
				? 'ПРЕДУПРЕЖДЕНИЕ'
				: alert.labels.severity.toUpperCase()
		: alert.labels.severity.toUpperCase()

	// Заголовок для алерта о смене оборудования
	const alertTitle = isHardwareChange
		? '⚠️ Обнаружено изменение конфигурации оборудования'
		: `🚨 ${alert.labels.alertname}`

	return `
        <div style="font-family: Arial, sans-serif; padding: 20px; max-width: 600px;">
            <h2 style="color: ${getSeverityColor(alert.labels.severity)}">
                ${alertTitle}
            </h2>
            <div style="margin: 20px 0; padding: 15px; border-left: 4px solid ${getSeverityColor(alert.labels.severity)}; background-color: #f9f9f9; border-radius: 4px;">
                <p><strong>${statusText}:</strong> ${statusValue}</p>
                <p><strong>${severityText}:</strong> ${severityValue}</p>
                <p><strong>${descriptionText}:</strong> ${alert.annotations.description}</p>
                <p><strong>${instanceText}:</strong> ${alert.labels.instance}</p>
                <p><strong>${startedText}:</strong> ${new Date(alert.startsAt).toLocaleString()}</p>
                ${
					alert.status === 'resolved'
						? `<p><strong>${resolvedText}:</strong> ${new Date(alert.endsAt).toLocaleString()}</p>`
						: ''
				}
            </div>
            <div style="font-size: 12px; color: #666; text-align: center; margin-top: 20px;">
                <p>${generatedText}</p>
            </div>
        </div>
    `
}

export function generateAlertTelegramText(alert: Alert): string {
	// Проверяем, является ли это алертом о смене оборудования или другим типом алерта
	const isHardwareChange =
		alert.labels.alertname === 'Hardware_Change_Detected' ||
		alert.labels.category === 'hardware_change'

	// Всегда используем русский язык для всех уведомлений
	const alertTitle = isHardwareChange
		? '⚠️ Обнаружено изменение конфигурации оборудования'
		: `🚨 ${alert.labels.alertname}`

	const statusText = 'Статус'
	const severityText = 'Приоритет'
	const descriptionText = 'Описание'
	const instanceText = 'Рабочее место'
	const startedText = 'Обнаружено'
	const resolvedText = 'Устранено'

	// Русские значения для статуса и серьезности
	const statusValue =
		alert.status.toUpperCase() === 'FIRING' ? 'АКТИВЕН' : 'УСТРАНЕН'
	const severityValue =
		alert.labels.severity.toUpperCase() === 'CRITICAL'
			? 'КРИТИЧЕСКАЯ'
			: alert.labels.severity.toUpperCase() === 'WARNING'
				? 'ПРЕДУПРЕЖДЕНИЕ'
				: alert.labels.severity.toUpperCase()

	// Форматирование даты в русском стиле
	const formatDate = (date: string) => {
		return new Date(date).toLocaleString('ru-RU', {
			day: '2-digit',
			month: '2-digit',
			year: 'numeric',
			hour: '2-digit',
			minute: '2-digit',
			second: '2-digit'
		})
	}

	return `
${alertTitle}
*${statusText}:* ${statusValue}
*${severityText}:* ${severityValue}
*${descriptionText}:* ${alert.annotations.description}
*${instanceText}:* ${alert.labels.instance}
*${startedText}:* ${formatDate(alert.startsAt)}
${alert.status === 'resolved' ? `*${resolvedText}:* ${formatDate(alert.endsAt)}` : ''}
`.trim()
}

function getSeverityColor(severity: string): string {
	switch (severity.toLowerCase()) {
		case 'critical':
			return '#dc3545'
		case 'warning':
			return '#ffc107'
		default:
			return '#17a2b8'
	}
}
