groups:
    - name: agent_status_alerts
      rules:
          - alert: Контроль статуса агента 107
            expr: up{instance=~"^192.168.13.107(:.*)?$"} == 0
            for: 5m
            labels:
                severity: warning
                category: agent_status
                instance: 192.168.13.107
            annotations:
                summary: ''
                description: |-
                    Рабочее место: {{ $labels.instance }}
                    Текущее значение: {{ $value }}
                    Пороговое значение: 0
          - alert: контроль 59
            expr: up{instance=~"^192.168.13.59(:.*)?$"} == 0
            for: 5m
            labels:
                severity: warning
                category: agent_status
                instance: 192.168.13.59
            annotations:
                summary: ''
                description: |-
                    Рабочее место: {{ $labels.instance }}
                    Текущее значение: {{ $value }}
                    Пороговое значение: 0
    - name: hardware_change_alerts
      rules:
          - alert: Контроль оборудования
            expr: Hardware_Change_Detected == 1
            for: 0s
            labels:
                severity: warning
                category: hardware_change
            annotations:
                summary: Конфигурация оборудования была изменена на {{ $labels.instance }}
                description: >-
                    Рабочее место: {{ $labels.instance }}

                    Конфигурация оборудования была изменена с момента последнего
                    запуска.
    - name: network_monitoring_alerts
      rules:
          - alert: Контроль сети статус
            expr: up == 0
            for: 5m
            labels:
                severity: warning
                category: network_monitoring
            annotations:
                summary: ''
                description: |-
                    Рабочее место: {{ $labels.instance }}
                    Текущее значение: {{ $value }}
                    Пороговое значение: 0
