groups:
  - name: hardware_change_alerts
    rules:
      - alert: Hardware_Change_Detected
        expr: UNIQUE_ID_CHANGED == 1
        for: 0m
        labels:
          severity: critical
          category: hardware_change
        annotations:
          summary: "Конфигурация оборудования была изменена на  {{ $labels.instance }}"
          description: |
            Рабочее место: {{ $labels.instance }}
            Конфигурация оборудования была изменена с момента последнего запуска.

