-- Seed default active license REMOVED for production
-- This file is intentionally left empty (except for this comment) to prevent
-- automatic creation of a default license in production environments.
